name: Releases

on:
  workflow_dispatch:

jobs:
  upload-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run build
        uses: ./.github/actions/build-linux
        with:
          go-version: '1.20'
          upload: true
