name: Unit tests
on: [push, pull_request]
jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run build
        uses: ./.github/actions/build-linux
        with:
          go-version: 1.19
      - name: Run lint
        uses: golangci/golangci-lint-action@v3
      - name: Run tests
        run: make cover
      - name: Convert coverage to lcov
        uses: jandelgado/gcov2lcov-action@v1.0.9
      - name: Coveralls
        uses: coverallsapp/github-action@v1.1.2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: coverage.lcov
  macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run build
        uses: ./.github/actions/build-macos
        with:
          go-version: 1.19
      - name: Run tests
        # We are not currently running the tests on macOS because the brew install doesn't
        # fix the Kext-Loading. The tests must remain disabled until GitHub provides a macOS
        # image with macfuse preinstalled, or some other viable solution pops up.
        # See https://github.com/osxfuse/osxfuse/issues/879#issuecomment-1114140186 for more info
        if: false
        shell: bash
        run: CGO_ENABLED=0 go test ./...
  windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run build
        uses: ./.github/actions/build-windows
        with:
          go-version: 1.19
      - name: Run tests
        shell: bash
        run: CGO_ENABLED=0 go test ./...
