name: Unit tests
on: [push, pull_request]
jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - name: install dependencies
        run: |
          sudo rm -f /etc/apt/sources.list.d/google-chrome.list
          sudo apt-get update
          sudo apt-get install -y libfuse-dev
      - uses: actions/checkout@v3
      - name: Setup go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18
      - name: Run lint
        uses: golangci/golangci-lint-action@v3
      - name: Run tests
        run: make cover
      - name: Convert coverage to lcov
        uses: jandelgado/gcov2lcov-action@v1.0.9
      - name: Coveralls
        uses: coverallsapp/github-action@v1.1.2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: coverage.lcov
  macos:
    runs-on: macos-latest
    steps:
      - name: install dependencies
        run: |
          brew update
          brew install --cask macfuse
      - uses: actions/checkout@v3
      - name: Setup go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18
      - name: Run lint
        uses: golangci/golangci-lint-action@v3
# We are not currently running the tests on macOS because the brew install doesn't
# fix the Kext-Loading. The tests must remain disabled until GitHub provides a macOS
# image with macfuse preinstalled, or some other viable solution pops up.
# See https://github.com/osxfuse/osxfuse/issues/879#issuecomment-1114140186 for more info
#      - name: Run tests
#        run: make test
